GROUP_REPOS = [
    {
        "name": "Team AB",
        "gitLinks": ["https://github.com/Team-AB-DevOps/ab-dev-ops"],
        "backend": "https://abdevops.dk",
        "frontend": "https://abdevops.dk",
        "monitoring": "https://monitoring.abdevops.dk",
        "stack": ["React TSX", "C# .NET"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "CEM",
        "gitLinks": ["https://github.com/CEM-KEA/whoknows"],
        "backend": "https://cemdev.dk",
        "frontend": "https://cemdev.dk",
        "monitoring": "https://monitor.cemdev.dk/grafana/",
        "stack": ["Go with Gorilla/mux", "React"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "Ukendt Gruppe",
        "gitLinks": ["https://github.com/ukendt-gruppe/whoKnows"],
        "backend": "https://monkbusiness.dk",
        "frontend": "https://monkbusiness.dk",
        "monitoring": "",
        "stack": ["Go w. Gorilla"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "LAWNE-KEA",
        "gitLinks": ["https://github.com/LAWNE-KEA/WhoKnows-Backend", "https://github.com/LAWNE-KEA/WhoKnows-Frontend"],
        "backend": "https://www.lawne.dk",
        "frontend": "http://www.lawne.dk",
        "monitoring": "",
        "stack": [Go w. gorm/gorilla],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "OBS",
        "gitLinks": ["https://github.com/OBS-DevOps24/whoknows-legacy"],
        "backend": "https://devobs.dk/",
        "frontend": "https://devobs.dk/",
        "monitoring": "http://20.234.170.235:3001",
        "stack": ["React, typescript", "C# .NET"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "MadeInChina-DevOps",
        "gitLinks": ["https://github.com/MadeInChina-DevOps/whoknowssearch"],
        "backend": "https://whoknowssearch.com",
        "frontend": "https://whoknowssearch.com",
        "monitoring": "https://monitor.whoknowssearch.com/",
        "stack": ["Rust", "Rocket", "PostgreSQL"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "UpsDev42069",
        "gitLinks": ["https://github.com/UpsDev42069/BM_Search_Engine"],
        "backend": "https://whonose.dk",
        "frontend": "https://whonose.dk",
        "monitoring": "http://13.79.97.206:3000",
        "stack": ["Go", "Gorilla/mux", "PostgreSQL", "Svelte"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "ITA",
        "gitLinks": ["https://github.com/IT-Arkitektur/whoknows_variations"],
        "backend": "",
        "frontend": "",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "Integration Nation",
        "gitLinks": ["https://github.com/Integration-Nation/DevOps-Project", "https://github.com/Integration-Nation/DevOps-Project-Frontend"],
        "backend": "https://integration-nation.dk:9090",
        "frontend": "https://integration-nation.dk",
        "monitoring": "http://52.169.123.180:3000/d/ee4gpboxbdp8gf/whoknows?from=now-6h&to=now&timezone=browser",
        "stack": ["Go", "Fiber", "Gorm", "Docker", "AzureVM", "PostgreSQL"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "Team-Dood",
        "gitLinks": ["https://github.com/Team-DooD/Whoknows"],
        "backend": "https://teamdood.dk",
        "frontend": "https://teamdood.dk",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "Team2-NM",
        "gitLinks": ["https://github.com/Team2-MN/whoknows_variations.git"],
        "backend": "",
        "frontend": "",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    },
    {
    "name": "AN-devOps",
    "gitLinks": ["https://github.com/Team-AN-devOps/whoknows_variations"],
    "backend": "http://167.99.41.21:4567",
    "frontend": "http://167.99.41.21:4567",
    "monitoring": "",
    "stack": ["Ruby Sinatra", "html"],
    "documentation": [],
    "sla": "",
}

]
