GROUP_REPOS = [
    {
        "name": "Team AB",
        "gitLinks": ["https://github.com/Team-AB-DevOps/ab-dev-ops"],
        "backend": "http://67.207.73.30:8081",
        "frontend": "http://67.207.73.30:8080",
        "monitoring": "",
        "stack": ["React TSX", "C# .NET"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "CEM",
        "gitLinks": ["https://github.com/CEM-KEA/whoknows"],
        "backend": "http://52.169.32.176:8080",
        "frontend": "http://52.169.32.176",
        "monitoring": "",
        "stack": ["Go with Gorilla/mux", "React"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "Ukendt Gruppe",
        "gitLinks": ["https://github.com/ukendt-gruppe/whoKnows"],
        "backend": "http://52.169.19.77:8080",
        "frontend": "http://52.169.19.77:8080",
        "monitoring": "",
        "stack": ["Go w. Gorilla"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "LAWNE-KEA",
        "gitLinks": ["https://github.com/LAWNE-KEA/WhoKnows-Backend", "https://github.com/LAWNE-KEA/WhoKnows-Frontend"],
        "backend": "http://100.25.126.145:8080",
        "frontend": "http://100.25.126.145:8080",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "OBS",
        "gitLinks": ["https://github.com/OBS-DevOps24/whoknows-legacy"],
        "backend": "http://52.164.251.63",
        "frontend": "http://52.164.251.63",
        "monitoring": "",
        "stack": ["React, typescript", "C# .NET"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "MadeInChina-DevOps",
        "gitLinks": ["https://github.com/MadeInChina-DevOps/whoknows_nooneknows"],
        "backend": "http://49.13.163.245/",
        "frontend": "http://49.13.163.245/",
        "monitoring": "",
        "stack": ["Rust", "Rocket", "PostgreSQL"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "UpsDev42069",
        "gitLinks": ["https://github.com/UpsDev42069/BM_Search_Engine"],
        "backend": "http://13.79.97.206:8080",
        "frontend": "http://13.79.97.206:8069",
        "monitoring": "",
        "stack": ["Go", "Gorilla/mux", "SQLite3", "Svelte"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "ITA",
        "gitLinks": ["https://github.com/IT-Arkitektur/whoknows_variations"],
        "backend": "",
        "frontend": "",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "Integration Nation",
        "gitLinks": ["https://github.com/Integration-Nation/DevOps-Project", "https://github.com/Integration-Nation/DevOps-Project-Frontend"],
        "backend": "https://40-85-136-203.nip.io:9090",
        "frontend": "https://40-85-136-203.nip.io",
        "monitoring": "",
        "stack": ["Go Fiber,Gorm, Docker, AzureVM, sqlite"],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "Team-Dood",
        "gitLinks": ["https://github.com/Team-DooD/Whoknows"],
        "backend": "https://teamdood.dk",
        "frontend": "https://teamdood.dk",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    },
    {
        "name": "Team2-NM",
        "gitLinks": ["https://github.com/Team2-MN/whoknows_variations.git"],
        "backend": "",
        "frontend": "",
        "monitoring": "",
        "stack": [],
        "documentation": [],
        "sla": "",
    },
    {
    "name": "AN-devOps",
    "gitLinks": ["https://github.com/Team-AN-devOps/whoknows_variations"],
    "backend": "http://167.99.41.21:4567",
    "frontend": "http://167.99.41.21:4567",
    "monitoring": "",
    "stack": ["Ruby Sinatra", "html"],
    "documentation": [],
    "sla": "",
}

]
