GROUP_REPOS = [
        {
            "name": "Example Group",
            "gitLinks": [""],
            "backend": "http(s)://<IP/DOMAIN>/<APIURL>",
            "frontend": "http(s)://<IP/DOMAIN>/<FrontEndURL>",
            "monitoring": "http(s)://<IP/DOMAIN>/<MonitoringURL>",
            "stack": ["Flask", "Svelte", "CouchDB", "Redis"],
            "documentation": ["link to documentation", "another link if it applies", "et cetera"],
            "sla": "link to sla",
        },
        {
            "name": "Team AB",
            "gitLinks": ["https://github.com/Team-AB-DevOps/ab-dev-ops"],
            "backend": "",
            "frontend": "",
            "monitoring": "",
            "stack": [],
            "documentation": [],
            "sla": "",
        },
        {
            "name": "CEM",
            "gitLinks": ["https://github.com/CEM-KEA/whoknows"],
            "backend": "",
            "frontend": "",
            "monitoring": "",
            "stack": [],
            "documentation": [],
            "sla": "",
        },
]
